// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: internal/positions/proto/positions.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry_StateId int32

const (
	Entry_Error                Entry_StateId = 0
	Entry_Waiting              Entry_StateId = 1
	Entry_WaitingForMission    Entry_StateId = 2
	Entry_WaitingForPassengers Entry_StateId = 3
	Entry_AlightingPassengers  Entry_StateId = 4
	Entry_BoardingPassengers   Entry_StateId = 5
	Entry_DrivingOnNetwork     Entry_StateId = 6
)

// Enum value maps for Entry_StateId.
var (
	Entry_StateId_name = map[int32]string{
		0: "Error",
		1: "Waiting",
		2: "WaitingForMission",
		3: "WaitingForPassengers",
		4: "AlightingPassengers",
		5: "BoardingPassengers",
		6: "DrivingOnNetwork",
	}
	Entry_StateId_value = map[string]int32{
		"Error":                0,
		"Waiting":              1,
		"WaitingForMission":    2,
		"WaitingForPassengers": 3,
		"AlightingPassengers":  4,
		"BoardingPassengers":   5,
		"DrivingOnNetwork":     6,
	}
)

func (x Entry_StateId) Enum() *Entry_StateId {
	p := new(Entry_StateId)
	*p = x
	return p
}

func (x Entry_StateId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entry_StateId) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_positions_proto_positions_proto_enumTypes[0].Descriptor()
}

func (Entry_StateId) Type() protoreflect.EnumType {
	return &file_internal_positions_proto_positions_proto_enumTypes[0]
}

func (x Entry_StateId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Entry_StateId.Descriptor instead.
func (Entry_StateId) EnumDescriptor() ([]byte, []int) {
	return file_internal_positions_proto_positions_proto_rawDescGZIP(), []int{1, 0}
}

type SimResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScenarioId         uint64  `protobuf:"varint,1,opt,name=scenarioId,proto3" json:"scenarioId,omitempty"`
	Entry              *Entry  `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	Period             *Period `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	MobilityProviderId uint64  `protobuf:"varint,4,opt,name=mobilityProviderId,proto3" json:"mobilityProviderId,omitempty"`
}

func (x *SimResult) Reset() {
	*x = SimResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_positions_proto_positions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResult) ProtoMessage() {}

func (x *SimResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_positions_proto_positions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResult.ProtoReflect.Descriptor instead.
func (*SimResult) Descriptor() ([]byte, []int) {
	return file_internal_positions_proto_positions_proto_rawDescGZIP(), []int{0}
}

func (x *SimResult) GetScenarioId() uint64 {
	if x != nil {
		return x.ScenarioId
	}
	return 0
}

func (x *SimResult) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *SimResult) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *SimResult) GetMobilityProviderId() uint64 {
	if x != nil {
		return x.MobilityProviderId
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId    uint64                   `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Capacity   uint32                   `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Load       uint32                   `protobuf:"varint,3,opt,name=load,proto3" json:"load,omitempty"`
	Position   []*Position              `protobuf:"bytes,4,rep,name=position,proto3" json:"position,omitempty"`
	StateId    Entry_StateId            `protobuf:"varint,5,opt,name=stateId,proto3,enum=positions.Entry_StateId" json:"stateId,omitempty"`
	Timestamps []*timestamppb.Timestamp `protobuf:"bytes,6,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_positions_proto_positions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_positions_proto_positions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_internal_positions_proto_positions_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetAgentId() uint64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *Entry) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Entry) GetLoad() uint32 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *Entry) GetPosition() []*Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Entry) GetStateId() Entry_StateId {
	if x != nil {
		return x.StateId
	}
	return Entry_Error
}

func (x *Entry) GetTimestamps() []*timestamppb.Timestamp {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude float32 `protobuf:"fixed32,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  float32 `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_positions_proto_positions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_internal_positions_proto_positions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_internal_positions_proto_positions_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Position) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *Period) Reset() {
	*x = Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_positions_proto_positions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_internal_positions_proto_positions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_internal_positions_proto_positions_proto_rawDescGZIP(), []int{3}
}

func (x *Period) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Period) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type GetEntriesPositionsFromScenarioIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScenarioId uint64 `protobuf:"varint,1,opt,name=scenarioId,proto3" json:"scenarioId,omitempty"`
}

func (x *GetEntriesPositionsFromScenarioIdRequest) Reset() {
	*x = GetEntriesPositionsFromScenarioIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_positions_proto_positions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntriesPositionsFromScenarioIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesPositionsFromScenarioIdRequest) ProtoMessage() {}

func (x *GetEntriesPositionsFromScenarioIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_positions_proto_positions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesPositionsFromScenarioIdRequest.ProtoReflect.Descriptor instead.
func (*GetEntriesPositionsFromScenarioIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_positions_proto_positions_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntriesPositionsFromScenarioIdRequest) GetScenarioId() uint64 {
	if x != nil {
		return x.ScenarioId
	}
	return 0
}

type GetEntriesPositionsFromScenarioIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *GetEntriesPositionsFromScenarioIdResponse) Reset() {
	*x = GetEntriesPositionsFromScenarioIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_positions_proto_positions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntriesPositionsFromScenarioIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesPositionsFromScenarioIdResponse) ProtoMessage() {}

func (x *GetEntriesPositionsFromScenarioIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_positions_proto_positions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesPositionsFromScenarioIdResponse.ProtoReflect.Descriptor instead.
func (*GetEntriesPositionsFromScenarioIdResponse) Descriptor() ([]byte, []int) {
	return file_internal_positions_proto_positions_proto_rawDescGZIP(), []int{5}
}

func (x *GetEntriesPositionsFromScenarioIdResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_internal_positions_proto_positions_proto protoreflect.FileDescriptor

var file_internal_positions_proto_positions_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x09, 0x53, 0x69, 0x6d, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x06,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52,
	0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x12, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8f, 0x03, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2f, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x12, 0x3a, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x22, 0x99, 0x01,
	0x0a, 0x07, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x10,
	0x01, 0x12, 0x15, 0x0a, 0x11, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x57, 0x61, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73,
	0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x69, 0x6e, 0x67, 0x50,
	0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x42,
	0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x73, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x72, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x4f, 0x6e,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x10, 0x06, 0x22, 0x44, 0x0a, 0x08, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22,
	0x30, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e,
	0x64, 0x22, 0x4a, 0x0a, 0x28, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x22, 0x53, 0x0a,
	0x29, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x32, 0xa6, 0x01, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x92, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x46, 0x72,
	0x6f, 0x6d, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x33, 0x2e, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x46, 0x72, 0x6f, 0x6d,
	0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x34, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_positions_proto_positions_proto_rawDescOnce sync.Once
	file_internal_positions_proto_positions_proto_rawDescData = file_internal_positions_proto_positions_proto_rawDesc
)

func file_internal_positions_proto_positions_proto_rawDescGZIP() []byte {
	file_internal_positions_proto_positions_proto_rawDescOnce.Do(func() {
		file_internal_positions_proto_positions_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_positions_proto_positions_proto_rawDescData)
	})
	return file_internal_positions_proto_positions_proto_rawDescData
}

var file_internal_positions_proto_positions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_positions_proto_positions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_positions_proto_positions_proto_goTypes = []interface{}{
	(Entry_StateId)(0), // 0: positions.Entry.StateId
	(*SimResult)(nil),  // 1: positions.SimResult
	(*Entry)(nil),      // 2: positions.Entry
	(*Position)(nil),   // 3: positions.Position
	(*Period)(nil),     // 4: positions.Period
	(*GetEntriesPositionsFromScenarioIdRequest)(nil),  // 5: positions.GetEntriesPositionsFromScenarioIdRequest
	(*GetEntriesPositionsFromScenarioIdResponse)(nil), // 6: positions.GetEntriesPositionsFromScenarioIdResponse
	(*timestamppb.Timestamp)(nil),                     // 7: google.protobuf.Timestamp
}
var file_internal_positions_proto_positions_proto_depIdxs = []int32{
	2, // 0: positions.SimResult.entry:type_name -> positions.Entry
	4, // 1: positions.SimResult.period:type_name -> positions.Period
	3, // 2: positions.Entry.position:type_name -> positions.Position
	0, // 3: positions.Entry.stateId:type_name -> positions.Entry.StateId
	7, // 4: positions.Entry.timestamps:type_name -> google.protobuf.Timestamp
	2, // 5: positions.GetEntriesPositionsFromScenarioIdResponse.entry:type_name -> positions.Entry
	5, // 6: positions.PositionService.GetEntriesPositionsFromScenarioId:input_type -> positions.GetEntriesPositionsFromScenarioIdRequest
	6, // 7: positions.PositionService.GetEntriesPositionsFromScenarioId:output_type -> positions.GetEntriesPositionsFromScenarioIdResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_positions_proto_positions_proto_init() }
func file_internal_positions_proto_positions_proto_init() {
	if File_internal_positions_proto_positions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_positions_proto_positions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_positions_proto_positions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_positions_proto_positions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_positions_proto_positions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_positions_proto_positions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntriesPositionsFromScenarioIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_positions_proto_positions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEntriesPositionsFromScenarioIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_positions_proto_positions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_positions_proto_positions_proto_goTypes,
		DependencyIndexes: file_internal_positions_proto_positions_proto_depIdxs,
		EnumInfos:         file_internal_positions_proto_positions_proto_enumTypes,
		MessageInfos:      file_internal_positions_proto_positions_proto_msgTypes,
	}.Build()
	File_internal_positions_proto_positions_proto = out.File
	file_internal_positions_proto_positions_proto_rawDesc = nil
	file_internal_positions_proto_positions_proto_goTypes = nil
	file_internal_positions_proto_positions_proto_depIdxs = nil
}
