version: "3.8"
services: 
  geotwin-grpctest:
    container_name: geotwin-grpctest
    build:
      args: 
        WORK_DIR: /go/src/github.com/MydroX/geotwin-grpctest
      context: ../
      dockerfile: ./deploy/Dockerfile
    ports:
      - 3000:3000
    volumes: 
      - ../.:/go/src/github.com/MydroX/geotwin-grpctest
    networks: 
      - "geotwin-grpc"

  geotwin-grpctest-db:
    container_name: geotwin-grpctest-db
    image: arangodb:3.6.16
    ports: 
      - "8529:8529"
    env_file: 
      - ../.env
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
    networks:
      - "geotwin-grpc"

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:

networks:
  geotwin-grpc:
    external: true